# TOOL node specifications
from .DISCORD_MCP_TOOL import DISCORD_MCP_TOOL_SPEC
from .FIRECRAWL_MCP_TOOL import FIRECRAWL_MCP_TOOL_SPEC
from .GOOGLE_CALENDAR_MCP_TOOL import GOOGLE_CALENDAR_MCP_TOOL_SPEC
from .NOTION_MCP_TOOL import NOTION_MCP_TOOL_SPEC
from .SLACK_MCP_TOOL import SLACK_MCP_TOOL_SPEC

__all__ = [
    "NOTION_MCP_TOOL_SPEC",
    "GOOGLE_CALENDAR_MCP_TOOL_SPEC",
    "SLACK_MCP_TOOL_SPEC",
    "FIRECRAWL_MCP_TOOL_SPEC",
    "DISCORD_MCP_TOOL_SPEC",
]
