
services:
  postgres:
    image: postgres:13
    container_name: postgres_workflow
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: workflow_engine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:6-alpine
    container_name: redis_workflow
    ports:
      - "6379:6379"
    networks:
      - app-network

  workflow-engine:
    build:
      context: .
      dockerfile: ./workflow_engine/Dockerfile
    container_name: workflow_engine_service
    ports:
      - "50050:50050"
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "50050"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 180s
    networks:
      - app-network

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    container_name: api_gateway_service
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - WORKFLOW_SERVICE_HOST=workflow-engine
      - WORKFLOW_SERVICE_PORT=50050
    depends_on:
      workflow-engine:
        condition: service_healthy
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
