version: '3.8'

# Development override configuration
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  # API Gateway - Development configuration
  api-gateway:
    environment:
      - DEBUG=true
    ports:
      - "8000:8000"
      - "5678:5678"  # For debugger if needed
    volumes:
      # Mount source code for hot reloading in development
      - ./api-gateway/app:/app/app:rw
      - ./shared/proto:/app/shared/proto:ro
    command: ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # Workflow Agent - Development configuration  
  workflow-agent:
    environment:
      - DEBUG=true
    ports:
      - "50051:50051"
      - "8001:8001"  # Debug server
      - "5679:5679"  # For debugger if needed
    volumes:
      # Mount source code for development
      - ./workflow_agent:/app:rw
      - ./shared/proto:/app/shared/proto:ro

  # Development tools
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  # Redis Commander for Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    hostname: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis