[project]
name = "workflow-agent-backend"
version = "1.0.0"
description = "Backend services for Workflow Agent Team - API Gateway and Workflow Agent"
authors = [
    {name = "Workflow Agent Team", email = "team@example.com"}
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.11"

# Workspace configuration for managing multiple packages
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest==7.4.3",
    "pytest-asyncio==0.21.1",
    "httpx==0.25.2",
    "black==23.11.0",
    "isort==5.12.0",
    "flake8==6.1.0",
    "mypy==1.7.1",
    "pre-commit==3.6.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["api-gateway", "workflow_agent"]

[tool.black]
line-length = 100
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 100

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

# Workspace settings
[tool.uv.workspace]
members = ["api-gateway", "workflow_agent"]