# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import workflow_agent_pb2 as workflow__agent__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/workflow_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkflowAgentStub(object):
    """唯一的核心接口 - 处理所有6阶段的对话流程和workflow生成
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessConversation = channel.unary_stream(
                '/workflow_agent.WorkflowAgent/ProcessConversation',
                request_serializer=workflow__agent__pb2.ConversationRequest.SerializeToString,
                response_deserializer=workflow__agent__pb2.ConversationResponse.FromString,
                _registered_method=True)


class WorkflowAgentServicer(object):
    """唯一的核心接口 - 处理所有6阶段的对话流程和workflow生成
    """

    def ProcessConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkflowAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessConversation': grpc.unary_stream_rpc_method_handler(
                    servicer.ProcessConversation,
                    request_deserializer=workflow__agent__pb2.ConversationRequest.FromString,
                    response_serializer=workflow__agent__pb2.ConversationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'workflow_agent.WorkflowAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('workflow_agent.WorkflowAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkflowAgent(object):
    """唯一的核心接口 - 处理所有6阶段的对话流程和workflow生成
    """

    @staticmethod
    def ProcessConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/workflow_agent.WorkflowAgent/ProcessConversation',
            workflow__agent__pb2.ConversationRequest.SerializeToString,
            workflow__agent__pb2.ConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
