# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import workflow_agent_pb2 as workflow__agent__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in workflow_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkflowAgentStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateWorkflow = channel.unary_unary(
                '/workflow_agent.WorkflowAgent/GenerateWorkflow',
                request_serializer=workflow__agent__pb2.WorkflowGenerationRequest.SerializeToString,
                response_deserializer=workflow__agent__pb2.WorkflowGenerationResponse.FromString,
                _registered_method=True)
        self.RefineWorkflow = channel.unary_unary(
                '/workflow_agent.WorkflowAgent/RefineWorkflow',
                request_serializer=workflow__agent__pb2.WorkflowRefinementRequest.SerializeToString,
                response_deserializer=workflow__agent__pb2.WorkflowRefinementResponse.FromString,
                _registered_method=True)
        self.ValidateWorkflow = channel.unary_unary(
                '/workflow_agent.WorkflowAgent/ValidateWorkflow',
                request_serializer=workflow__agent__pb2.WorkflowValidationRequest.SerializeToString,
                response_deserializer=workflow__agent__pb2.WorkflowValidationResponse.FromString,
                _registered_method=True)


class WorkflowAgentServicer(object):
    """Service definition
    """

    def GenerateWorkflow(self, request, context):
        """Generate workflow from natural language description
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefineWorkflow(self, request, context):
        """Refine existing workflow based on feedback
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateWorkflow(self, request, context):
        """Validate workflow structure and configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkflowAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateWorkflow,
                    request_deserializer=workflow__agent__pb2.WorkflowGenerationRequest.FromString,
                    response_serializer=workflow__agent__pb2.WorkflowGenerationResponse.SerializeToString,
            ),
            'RefineWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.RefineWorkflow,
                    request_deserializer=workflow__agent__pb2.WorkflowRefinementRequest.FromString,
                    response_serializer=workflow__agent__pb2.WorkflowRefinementResponse.SerializeToString,
            ),
            'ValidateWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateWorkflow,
                    request_deserializer=workflow__agent__pb2.WorkflowValidationRequest.FromString,
                    response_serializer=workflow__agent__pb2.WorkflowValidationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'workflow_agent.WorkflowAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('workflow_agent.WorkflowAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkflowAgent(object):
    """Service definition
    """

    @staticmethod
    def GenerateWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow_agent.WorkflowAgent/GenerateWorkflow',
            workflow__agent__pb2.WorkflowGenerationRequest.SerializeToString,
            workflow__agent__pb2.WorkflowGenerationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefineWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow_agent.WorkflowAgent/RefineWorkflow',
            workflow__agent__pb2.WorkflowRefinementRequest.SerializeToString,
            workflow__agent__pb2.WorkflowRefinementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow_agent.WorkflowAgent/ValidateWorkflow',
            workflow__agent__pb2.WorkflowValidationRequest.SerializeToString,
            workflow__agent__pb2.WorkflowValidationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
