global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # 可以在这里添加告警规则文件

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'workflow-agent'
    static_configs:
      - targets: ['host.docker.internal:8001']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'workflow-engine'
    static_configs:
      - targets: ['host.docker.internal:8002']
    metrics_path: /metrics
    scrape_interval: 10s