import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarNavigation } from "@/components/ui/sidebar-navigation";
import { LayoutWrapper } from "@/components/ui/layout-wrapper";
import { ThemeProvider } from "@/components/theme-provider";
import { AuthProvider } from "@/contexts/auth-context";
import { PageTitleProvider } from "@/contexts/page-title-context";
import { Toaster } from "@/components/ui/toaster";

const nunito = localFont({
  src: [
    {
      path: "../../public/fonts/nunito/Nunito-VariableFont_wght.ttf",
      style: "normal",
    },
    {
      path: "../../public/fonts/nunito/Nunito-Italic-VariableFont_wght.ttf",
      style: "italic",
    },
  ],
  variable: "--font-nunito",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Starmates",
  description: "Generated by Starmates.ai",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${nunito.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <AuthProvider>
            <PageTitleProvider>
              <LayoutWrapper>
                <SidebarNavigation />
                <main className="h-full">
                  {children}
                </main>
              </LayoutWrapper>
              <Toaster />
            </PageTitleProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
