import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SidebarNavigation } from "@/components/ui/sidebar-navigation";
import { LayoutWrapper } from "@/components/ui/layout-wrapper";
import { ThemeProvider } from "@/components/theme-provider";
import { AuthProvider } from "@/contexts/auth-context";
import { PageTitleProvider } from "@/contexts/page-title-context";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Starmates",
  description: "Generated by Starmates.ai",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <AuthProvider>
            <PageTitleProvider>
              <LayoutWrapper>
                <SidebarNavigation />
                <main className="h-full">
                  {children}
                </main>
              </LayoutWrapper>
              <Toaster />
            </PageTitleProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
