# TRIGGER node specifications
from .CRON import CRON_TRIGGER_SPEC
from .EMAIL import EMAIL_TRIGGER_SPEC
from .GITHUB import GITHUB_TRIGGER_SPEC
from .MANUAL import MANUAL_TRIGGER_SPEC
from .SLACK import SLACK_TRIGGER_SPEC
from .WEBHOOK import WEBHOOK_TRIGGER_SPEC

__all__ = [
    "MANUAL_TRIGGER_SPEC",
    "WEBHOOK_TRIGGER_SPEC",
    "CRON_TRIGGER_SPEC",
    "GITHUB_TRIGGER_SPEC",
    "SLACK_TRIGGER_SPEC",
    "EMAIL_TRIGGER_SPEC",
]
