create table public.chats (
  id bigint generated by default as identity not null,
  session_id uuid null default gen_random_uuid (),
  user_id uuid null default auth.uid (),
  message_type character varying null,
  content text null default ''::text,
  sequence_number integer null,
  created_at timestamp with time zone not null default now(),
  constraint chats_pkey primary key (id),
  constraint chats_session_id_fkey foreign KEY (session_id) references sessions (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;
